run:
  go: 1.19

linter-settings:
  misspell:
    locale: US

linters:
  enable:
    - gofumpt
    - unconvert
    - revive
    - forbidigo
    - tagliatelle
    - misspell
  disable:
    - structcheck
