[linters-settings]

  [linters-settings.misspell]
    locale = "US"

[linters]
  enable-all = true
  disable = [
    "maligned",
    "lll",
    "gomnd",
    "scopelint",
    "paralleltest",
    "nlreturn",
    "goconst",
    "nestif",
    "funlen",
    "varnamelen",
    "ireturn",
    "exhaustivestruct",
    "cyclop",
    "bodyclose", # https://github.com/timakin/bodyclose/pull/14
  ]

[issues]
    exclude-use-default = true
    [[issues.exclude-rules]]
      path = "internal/platform/providers/providers.go"
      linters = ["gocritic"]
    [[issues.exclude-rules]]
      linters = ["wsl"]
      text = "declarations should never be cuddled"
    [[issues.exclude-rules]]
      path = "cmd/ims/main.go"
      linters = ["gochecknoglobals"]
    [[issues.exclude-rules]]
      path = "(.+)_test.go"
      linters = ["funlen"]
    [[issues.exclude-rules]]
      path = "cmd/ims/app/server.go"
      linters = ["funlen"]
    [[issues.exclude-rules]]
      text = "ifElseChain: rewrite if-else to switch statement"
      linters = ["gocritic"]
    # TODO: revisit rule when we have time to address
    [[issues.exclude-rules]]
      path = "cmd/ims/app/server.go"
      text = "prometheus.InstrumentHandlerFunc is deprecated.*"
    # TODO: revisit rule when we have time to address
    [[issues.exclude-rules]]
      path = "cmd/ims/app/server.go"
      text = "prometheus.Handler is deprecated.*"