version: "2"

linters:
  default: none
  enable:
    - unconvert
    - revive
    - forbidigo
    - tagliatelle
    - misspell
  settings:
    misspell:
      locale: US
    revive:
      rules:
        - name: unused-parameter
          disabled: true
        - name: package-comments
          disabled: true
        - name: superfluous-else
          disabled: true

formatters:
  enable:
    - gofumpt
