project_name: ims

builds:
  - main: ./cmd/ims/main.go
    binary: ims
    env:
      - CGO_ENABLED=0
    flags:
      - -tags
      - netgo
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: 386

dockers:
  - image_templates:
      - "wyattjoh/ims:{{ .Tag }}"
      - "wyattjoh/ims:v{{ .Major }}.{{ .Minor }}"
      - "wyattjoh/ims:v{{ .Major }}"
      - "wyattjoh/ims:latest"
      - "ghcr.io/wyattjoh/ims:{{ .Tag }}"
      - "ghcr.io/wyattjoh/ims:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/wyattjoh/ims:v{{ .Major }}"
      - "ghcr.io/wyattjoh/ims:latest"

brews:
  - github:
      owner: wyattjoh
      name: homebrew-stable
    folder: Formula
    homepage: https://github.com/wyattjoh/ims
    description: image manipulation service, written in Go
    test: |
      system "#{bin}/ims -v"
    install: |
      bin.install "ims"

archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - README.md

release:
  github:
    owner: wyattjoh
    name: ims
