version: 2

project_name: ims

builds:
  - main: ./cmd/ims/main.go
    binary: ims
    env:
      - CGO_ENABLED=0
    flags:
      - -tags
      - netgo
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

dockers_v2:
  - id: ims
    dockerfile: Dockerfile
    images:
      - "wyattjoh/ims"
      - "ghcr.io/wyattjoh/ims"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "v{{ .Major }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64

homebrew_casks:
  - name: ims
    binaries:
      - ims
    repository:
      owner: wyattjoh
      name: homebrew-stable
    directory: Casks
    homepage: https://github.com/wyattjoh/ims
    description: image manipulation service, written in Go
    license: MIT

archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE.md
      - README.md

release:
  github:
    owner: wyattjoh
    name: ims
