language: go

go:
  - 1.x

env:
  global:
    - GO111MODULE=on

  # Install linters and misspell
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

install:
  - go mod tidy
  - git diff --exit-code go.mod
  - git diff --exit-code go.sum
  - go mod download

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true