name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          # Note the fetch-depth: 0 option is required for the change log to
          # work correctly with goreleaser.
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.0"
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.35
      - name: Unit testing
        run: go test ./...
      - name: Login to Docker Hub Docker Registry
        uses: docker/login-action@v1.13.0
        with:
          username: wyattjoh
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.13.0
        with:
          registry: ghcr.io
          username: wyattjoh
          password: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
      - uses: goreleaser/goreleaser-action@v2.9.1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
