name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Note the fetch-depth: 0 option is required for the change log to
          # work correctly with goreleaser.
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.24"
      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: Unit testing
        run: go test ./...
      - name: Login to Docker Hub Docker Registry
        uses: docker/login-action@v3
        with:
          username: wyattjoh
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: wyattjoh
          password: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
